server:
  port: 8090

spring:
  application:
    name: billing-batch
  batch:
    jdbc:
      initialize-schema: never

  datasource:
    url: jdbc:mysql://mysql:3306/billing_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379
redis:
  stream:
    message:
      key: message-stream
      consumer: billing-batch   # 추가 

message:
  stream: message-stream        # recovery에서 읽을 값이면 여기에
  group: message-group
  recovery:
    timeout-minutes: 60
    fixed-delay-ms: 300000
    claim-count: 10000
    db-batch-size: 10000